create table host (
    id                      integer     not null,
    create_time             integer,
    userid                  integer,
    rpc_seqno               integer,
    rpc_time                integer,
    total_credit            double ,
    expavg_credit           double ,
    expavg_time             double ,
    timezone                integer,
    domain_name             varchar(254),
    serialnum               varchar(254),
    last_ip_addr            varchar(254),
    nsame_ip_addr           integer,
    on_frac                 double ,
    connected_frac          double ,
    active_frac             double ,
    cpu_efficiency          double ,
    duration_correction_factor double,
    p_ncpus                 integer,
    p_vendor                varchar(254),
    p_model                 varchar(254),
    p_fpops                 double ,
    p_iops                  double ,
    p_membw                 double ,
    os_name                 varchar(254),
    os_version              varchar(254),
    m_nbytes                double ,
    m_cache                 double ,
    m_swap                  double ,
    d_total                 double ,
    d_free                  double ,
    d_boinc_used_total      double ,
    d_boinc_used_project    double ,
    d_boinc_max             double ,
    n_bwup                  double ,
    n_bwdown                double ,
    credit_per_cpu_sec      double ,
    venue                   varchar(254),
    nresults_today          integer,
    avg_turnaround          double ,
    host_cpid               varchar(254)    not null,
    external_ip_addr        varchar(254),
    max_results_day         integer,
    error_rate              double  default 0,
    product_name            varchar(254),
    gpu_active_frac         double ,
    primary key (id)
) engine=InnoDB;