wget "http://www.distributeddatamining.org/DistributedDataMining/team_email_list.php?teamid=2176&xml=1" -O /json/Stats/TeamStats/DDM.xml
wget "http://lhcathomeclassic.cern.ch/sixtrack/team_email_list.php?teamid=8128&xml=1" -O /json/Stats/TeamStats/LHCatHome.xml
wget "http://www.worldcommunitygrid.org/boinc/team_email_list.php?teamid=30513&xml=1" -O /json/Stats/TeamStats/WCG.xml
wget "http://finance.gridcoin.us/finance/team_email_list.php?teamid=5&xml=1" -O /json/Stats/TeamStats/GRCF.xml
wget "http://www.gpugrid.net/team_email_list.php?teamid=3493&xml=1" -O /json/Stats/TeamStats/GPUGrid.xml
wget "http://asteroidsathome.net/boinc/team_email_list.php?teamid=2218&xml=1" -O /json/Stats/TeamStats/Asteroids.xml
wget "http://milkyway.cs.rpi.edu/milkyway/team_email_list.php?teamid=6566&xml=1" -O /json/Stats/TeamStats/Milkyway.xml
wget "http://boinc.fzk.de/poem/team_email_list.php?teamid=3147&xml=1" -O /json/Stats/TeamStats/POEM.xml
wget "http://boinc.thesonntags.com/collatz/team_email_list.php?teamid=3029&xml=1" -O /json/Stats/TeamStats/Collatz.xml
wget "https://einstein.phys.uwm.edu/team_email_list.php?teamid=13630&xml=1" -O /json/Stats/TeamStats/Einstein.xml
wget "http://www.primegrid.com/team_email_list.php?teamid=4469&xml=1" -O /json/Stats/TeamStats/Primegrid.xml
wget "http://setiathome.berkeley.edu/team_email_list.php?teamid=145340&xml=1" -O /json/Stats/TeamStats/SETI.xml
wget "http://csgrid.org/csg/team_email_list.php?teamid=154&xml=1" -O /json/Stats/TeamStats/CSG.xml
wget "http://burp.renderfarming.net/team_email_list.php?teamid=1285&xml=1" -O /json/Stats/TeamStats/BURP.xml
wget "http://yafu.myfirewall.org/yafu/team_email_list.php?teamid=260&xml=1" -O /json/Stats/TeamStats/YAFU.xml
wget "http://findah.ucd.ie/team_email_list.php?teamid=2198&xml=1" -O /json/Stats/TeamStats/FIND.xml
wget "http://climateapps2.oerc.ox.ac.uk/cpdnboinc/team_email_list.php?teamid=10427&xml=1" -O /json/Stats/TeamStats/ClimatePrediction.xml
wget "http://www.cosmologyathome.org/team_email_list.php?teamid=3637&xml=1" -O /json/Stats/TeamStats/Cosmology.xml
wget "http://www.enigmaathome.net/team_email_list.php?teamid=2937&xml=1" -O /json/Stats/TeamStats/Enigma.xml
wget "http://boinc.gorlaeus.net/team_email_list.php?teamid=1629&xml=1" -O /json/Stats/TeamStats/LeidenClassic.xml
wget "http://lhcathome2.cern.ch/vLHCathome/team_email_list.php?teamid=2429&xml=1" -O /json/Stats/TeamStats/vLHC.xml
wget "http://www.malariacontrol.net/team_email_list.php?teamid=4059&xml=1" -O /json/Stats/TeamStats/Malariacontrol.xml
wget "http://mindmodeling.org/team_email_list.php?teamid=2415&xml=1" -O /json/Stats/TeamStats/MindModeling.xml
wget "http://escatter11.fullerton.edu/nfs/team_email_list.php?teamid=2353&xml=1" -O /json/Stats/TeamStats/NFS.xml
wget "http://numberfields.asu.edu/NumberFields/team_email_list.php?teamid=2069&xml=1" -O /json/Stats/TeamStats/NumbersField.xml
wget "http://boinc.bakerlab.org/rosetta/team_email_list.php?teamid=12575&xml=1" -O /json/Stats/TeamStats/Rosetta.xml
wget "http://sat.isa.ru/pdsat/team_email_list.php?teamid=2059&xml=1" -O /json/Stats/TeamStats/SAT.xml
wget "http://pogs.theskynet.org/pogs/team_email_list.php?teamid=2020&xml=1" -O /json/Stats/TeamStats/Skynet.xml
wget "http://www.rechenkraft.net/yoyo/team_email_list.php?teamid=1475&xml=1" -O /json/Stats/TeamStats/YOYO.xml
wget "http://www.bitcoinutopia.net/bitcoinutopia/team_email_list.php?teamid=1888&xml=1" -O /json/Stats/TeamStats/BU.xml
