wget "http://yafu.myfirewall.org/yafu/team_email_list.php?teamid=260&xml=1" -O /json/Stats/TeamStats/YAFU.xml
wget "http://climateapps2.oerc.ox.ac.uk/cpdnboinc/team_email_list.php?teamid=10427&xml=1" -O /json/Stats/TeamStats/ClimatePrediction.xml
wget "http://boinc.gorlaeus.net/team_email_list.php?teamid=1629&xml=1" -O /json/Stats/TeamStats/LeidenClassic.xml
wget "http://boinc.bakerlab.org/rosetta/team_email_list.php?teamid=12575&xml=1" -O /json/Stats/TeamStats/Rosetta.xml
wget "http://www.distributeddatamining.org/DistributedDataMining/team_email_list.php?teamid=2176&xml=1" -O /json/Stats/TeamStats/DDM.xml
wget "http://lhcathomeclassic.cern.ch/sixtrack/team_email_list.php?teamid=8128&xml=1" -O /json/Stats/TeamStats/LHCatHome.xml
wget "http://www.worldcommunitygrid.org/boinc/team_email_list.php?teamid=30513&xml=1" -O /json/Stats/TeamStats/WCG.xml
wget "http://wuprop.boinc-af.org/team_email_list.php?teamid=2243&xml=1" -O /json/Stats/TeamStats/Wuprop.xml
wget "http://finance.gridcoin.us/server_status.php?xml=1" -O /json/Stats/TeamStats/GRCF.xml