wget "http://lhcathomeclassic.cern.ch/sixtrack/server_status.php?xml=1" -O /json/Stats/ServerStatus/LHC.xml
wget "http://moowrap.net/server_status.php?xml=1" -O /json/Stats/ServerStatus/Moowrap.xml
wget "http://numberfields.asu.edu/NumberFields/server_status.xml" -O /json/Stats/ServerStatus/Numberfields.xml
wget "http://sat.isa.ru/pdsat/server_status.php?xml=1" -O /json/Stats/ServerStatus/SAT.xml
wget "http://boinc.thesonntags.com/collatz/server_status.php?xml=1" -O /json/Stats/ServerStatus/Collatz.xml
wget "http://escatter11.fullerton.edu/nfs/server_status.php?xml=1" -O /json/Stats/ServerStatus/NFS.xml
wget "http://www.primegrid.com/server_status.php?xml=1" -O /json/Stats/ServerStatus/Primegrid.xml
wget "http://yafu.myfirewall.org/yafu/server_status.php?xml=1" -O /json/Stats/ServerStatus/YAFU.xml
wget "http://setiathome.berkeley.edu/sah_status.xml" -O /json/Stats/ServerStatus/SETI.xml
wget "http://www.cosmologyathome.org/server_status.php?xml=1" -O /json/Stats/ServerStatus/Cosmologyathome.xml
wget "http://burp.renderfarming.net/server_status.php?xml=1" -O /json/Stats/ServerStatus/BURP.xml
wget "http://asteroidsathome.net/boinc/server_status.php?xml=1" -O /json/Stats/ServerStatus/Asteroids.xml
wget "http://pogs.theskynet.org/pogs/server_status.php?xml=1" -O /json/Stats/ServerStatus/Skynet.xml
wget "http://www.enigmaathome.net/server_status.php?xml=1" -O /json/Stats/ServerStatus/Enigma.xml
wget "https://einstein.phys.uwm.edu/server_status.php?xml=1" -O /json/Stats/ServerStatus/Einstein.xml
wget "http://milkyway.cs.rpi.edu/milkyway/server_status.php?xml=1" -O /json/Stats/ServerStatus/Milkyway.xml
wget "http://atlasathome.cern.ch/server_status.php?xml=1" -O /json/Stats/ServerStatus/Atlas.xml
wget "http://finance.gridcoin.us/server_status.php?xml=1" -O /json/Stats/ServerStatus/GridcoinFinance.xml
wget "http://www.bitcoinutopia.net/bitcoinutopia/server_status.php?xml=1" -O /json/Stats/ServerStatus/BU.xml
wget "http://mindmodeling.org/server_status.php?xml=1" -O /json/Stats/ServerStatus/MindModeling.xml
wget "http://volunteer.cs.und.edu/csg/server_status.php?xml=1" -O /json/Stats/ServerStatus/CSG.xml
wget "http://casathome.ihep.ac.cn/server_status.php?xml=1" -O /json/Stats/ServerStatus/CAS.xml
wget "http://www.rechenkraft.net/yoyo/server_status.php?xml=1" -O /json/Stats/ServerStatus/YOYO.xml
wget "http://findah.ucd.ie/server_status.php?xml=1" -O /json/Stats/ServerStatus/FAH.xml
wget "http://boinc.fzk.de/poem/server_status.php?xml=1" -O /json/Stats/ServerStatus/POEM.xml
wget "http://www.malariacontrol.net/server_status.php?xml=1" -O /json/Stats/ServerStatus/MalariaControl.xml
wget "https://www.gpugrid.net/server_status.php?xml=1" -O /json/Stats/ServerStatus/GPUGRID.xml