wget "http://asteroidsathome.net/boinc/team_email_list.php?teamid=2218&xml=1" -O ./XML/Asteroids.xml
wget "http://atlasathome.cern.ch/team_email_list.php?teamid=1869&xml=1" -O ./XML/Atlas.xml
wget "http://burp.renderfarming.net/team_email_list.php?teamid=1285&xml=1" -O ./XML/BURP.xml
wget "http://csgrid.org/csg/team_email_list.php?teamid=154&xml=1" -O ./XML/CSG.xml
wget "http://boinc.thesonntags.com/collatz/team_email_list.php?teamid=3029&xml=1" -O ./XML/Collatz.xml
wget "http://www.cosmologyathome.org/team_email_list.php?teamid=3637&xml=1" -O ./XML/Cosmology.xml
wget "http://climateapps2.oerc.ox.ac.uk/cpdnboinc/team_email_list.php?teamid=10427&xml=1" -O ./XML/CPDN.xml
wget "http://www.distributeddatamining.org/DistributedDataMining/team_email_list.php?teamid=2176&xml=1" -O ./XML/DDM.xml
wget "http://denis.usj.es/denisathome/team_email_list.php?teamid=1825&xml=1" -O ./XML/Denis.xml
wget "https://einstein.phys.uwm.edu/team_email_list.php?teamid=13630&xml=1" -O ./XML/Einstein.xml
wget "http://www.enigmaathome.net/team_email_list.php?teamid=2937&xml=1" -O ./XML/Enigma.xml
wget "http://findah.ucd.ie/team_email_list.php?teamid=2198&xml=1" -O ./XML/FindAtHome.xml
wget "http://www.gpugrid.net/team_email_list.php?teamid=3493&xml=1" -O ./XML/GPUGrid.xml
wget "http://finance.gridcoin.us/finance/team_email_list.php?teamid=5&xml=1" -O ./XML/GridcoinFinance.xml
wget "http://lhcathomeclassic.cern.ch/sixtrack/team_email_list.php?teamid=8128&xml=1" -O ./XML/LHCatHome.xml
wget "http://boinc.gorlaeus.net/team_email_list.php?teamid=1629&xml=1" -O ./XML/LeidenClassic.xml
wget "http://www.malariacontrol.net/team_email_list.php?teamid=4059&xml=1" -O ./XML/MalariaControl.xml
wget "http://milkyway.cs.rpi.edu/milkyway/team_email_list.php?teamid=6566&xml=1" -O ./XML/Milkyway.xml
wget "http://mindmodeling.org/team_email_list.php?teamid=2415&xml=1" -O ./XML/MindModeling.xml
wget "http://moowrap.net/team_email_list.php?teamid=2190&xml=1" -O ./XML/MooWrap.xml
wget "http://escatter11.fullerton.edu/nfs/team_email_list.php?teamid=2353&xml=1" -O ./XML/NFS.xml
wget "http://numberfields.asu.edu/NumberFields/team_email_list.php?teamid=2069&xml=1" -O ./XML/NumbersField.xml
wget "http://boinc.fzk.de/poem/team_email_list.php?teamid=3147&xml=1" -O ./XML/POEM.xml
wget "http://www.primegrid.com/team_email_list.php?teamid=4469&xml=1" -O ./XML/PrimeGrid.xml
wget "http://boinc.bakerlab.org/rosetta/team_email_list.php?teamid=12575&xml=1" -O ./XML/Rosetta.xml
wget "http://sat.isa.ru/pdsat/team_email_list.php?teamid=2059&xml=1" -O ./XML/SAT.xml
wget "http://setiathome.berkeley.edu/team_email_list.php?teamid=145340&xml=1" -O ./XML/SETI.xml
wget "http://pogs.theskynet.org/pogs/team_email_list.php?teamid=2020&xml=1" -O ./XML/Skynet.xml
wget "http://www.worldcommunitygrid.org/boinc/team_email_list.php?teamid=30513&xml=1" -O ./XML/WCG.xml
wget "http://yafu.myfirewall.org/yafu/team_email_list.php?teamid=260&xml=1" -O ./XML/YAFU.xml
wget "http://www.rechenkraft.net/yoyo/team_email_list.php?teamid=1475&xml=1" -O ./XML/YOYO.xml
wget "http://lhcathome2.cern.ch/vLHCathome/team_email_list.php?teamid=2429&xml=1" -O ./XML/vLHC.xml
wget "http://szdg.lpds.sztaki.hu/szdg/team_email_list.php?teamid=3502&xml=1" -O ./XML/Sztaki.xml
wget "http://wuprop.boinc-af.org/team_email_list.php?teamid=2243&xml=1" -O ./XML/Wuprop.xml
#Lattice's xml is malformed, don't enable until fixed. Could maybe remove the html above the xml content?
#wget "http://boinc.umiacs.umd.edu/team_email_list.php?teamid=3567&xml=1" -O ./XML/lattice2.xml
wget "https://grcnode.co.uk/Stats/Reports/DailyNeuralMagnitudeReport.csv" -O ./XML/NNReport.csv