USE TeamGridcoin;
create table TeamOverview (
    name                    varchar(254),
    country                 varchar(254),
    combined_total_credit            double,
    combined_expavg_credit           double,
    project_mag_Asteroids             double     DEFAULT 0,
    project_mag_Atlas             double     DEFAULT 0,
    project_mag_BU             double     DEFAULT 0,
    project_mag_BURP             double     DEFAULT 0,
    project_mag_CAS             double     DEFAULT 0,
    project_mag_CSG             double     DEFAULT 0,
    project_mag_Collatz             double     DEFAULT 0,
    project_mag_Cosmology             double     DEFAULT 0,
    project_mag_DDM             double     DEFAULT 0,
    project_mag_Einstein             double     DEFAULT 0,
    project_mag_Enigma             double     DEFAULT 0,
    project_mag_FIND             double     DEFAULT 0,
    project_mag_GPUGrid             double     DEFAULT 0,
    project_mag_GRCF             double     DEFAULT 0,
    project_mag_LHCatHome             double     DEFAULT 0,
    project_mag_LeidenClassic             double     DEFAULT 0,
    project_mag_Malariacontrol             double     DEFAULT 0,
    project_mag_Milkyway             double     DEFAULT 0,
    project_mag_MindModeling             double     DEFAULT 0,
    project_mag_NFS             double     DEFAULT 0,
    project_mag_NumbersField             double     DEFAULT 0,
    project_mag_POEM             double     DEFAULT 0,
    project_mag_Primegrid             double     DEFAULT 0,
    project_mag_Rosetta             double     DEFAULT 0,
    project_mag_SAT             double     DEFAULT 0,
    project_mag_SETI             double     DEFAULT 0,
    project_mag_Skynet             double     DEFAULT 0,
    project_mag_WCG             double     DEFAULT 0,
    project_mag_YAFU             double     DEFAULT 0,
    project_mag_YOYO             double     DEFAULT 0,
    project_mag_vLHC             double     DEFAULT 0,
    TotalMag             double     DEFAULT 0,
    MonthlyEarnings             double     DEFAULT 0,
    StakingAddress                 varchar(35),
    OP_Return                 varchar(254),
    cpid        varchar(254)         not null,
    primary key (cpid)
) engine=InnoDB;