wget "http://lhcathomeclassic.cern.ch/sixtrack/server_status.php?xml=1" -O LHC.xml
wget "http://moowrap.net/server_status.php?xml=1" -O Moowrap.xml
wget "http://numberfields.asu.edu/NumberFields/server_status.xml" -O Numberfields.xml
wget "http://sat.isa.ru/pdsat/server_status.php?xml=1" -O SAT.xml
wget "http://boinc.thesonntags.com/collatz/server_status.php?xml=1" -O Collatz.xml
wget "http://escatter11.fullerton.edu/nfs/server_status.php?xml=1" -O NFS.xml
wget "http://www.primegrid.com/server_status.php?xml=1" -O Primegrid.xml
wget "http://yafu.myfirewall.org/yafu/server_status.php?xml=1" -O YAFU.xml
wget "http://setiathome.berkeley.edu/sah_status.xml" -O SETI.xml
wget "http://www.cosmologyathome.org/server_status.php?xml=1" -O Cosmologyathome.xml
wget "http://burp.renderfarming.net/server_status.php?xml=1" -O BURP.xml
wget "http://asteroidsathome.net/boinc/server_status.php?xml=1" -O Asteroids.xml
wget "http://pogs.theskynet.org/pogs/server_status.php?xml=1" -O Skynet.xml
wget "http://www.enigmaathome.net/server_status.php?xml=1" -O Enigma.xml
wget "https://einstein.phys.uwm.edu/server_status.php?xml=1" -O Einstein.xml
wget "http://milkyway.cs.rpi.edu/milkyway/server_status.php?xml=1" -O Milkyway.xml
wget "http://atlasathome.cern.ch/server_status.php?xml=1" -O Atlas.xml
wget "http://finance.gridcoin.us/server_status.php?xml=1" -O GridcoinFinance.xml
wget "http://www.bitcoinutopia.net/bitcoinutopia/server_status.php?xml=1" -O BU.xml
wget "http://mindmodeling.org/server_status.php?xml=1" -O MindModeling.xml
wget "http://volunteer.cs.und.edu/csg/server_status.php?xml=1" -O CSG.xml
wget "http://casathome.ihep.ac.cn/server_status.php?xml=1" -O CAS.xml
wget "http://www.rechenkraft.net/yoyo/server_status.php?xml=1" -O YOYO.xml
wget "http://findah.ucd.ie/server_status.php?xml=1" -O FAH.xml
wget "http://boinc.fzk.de/poem/server_status.php?xml=1" -O POEM.xml
wget "http://www.malariacontrol.net/server_status.php?xml=1" -O MalariaControl.xml
wget "https://www.gpugrid.net/server_status.php?xml=1" -O GPUGRID.xml
wget "http://www.distributeddatamining.org/DistributedDataMining/server_status.php?xml=1" -O DDM.xml
wget "http://boinc.gorlaeus.net/server_status.php?xml=1" -O Leiden.xml
wget "http://lhcathome2.cern.ch/vLHCathome/server_status.php?xml=1" -O lhcathome2.xml
#CPDN server status page is html not php, unable to get xml extract.
#http://climateapps2.oerc.ox.ac.uk/cpdnboinc/server_status.html