clamscan ./XML/Asteroids.xml
clamscan ./XML/Atlas.xml
clamscan ./XML/BURP.xml
clamscan ./XML/CSG.xml
clamscan ./XML/Collatz.xml
clamscan ./XML/Cosmology.xml
clamscan ./XML/CPDN.xml
clamscan ./XML/DDM.xml
clamscan ./XML/Denis.xml
clamscan ./XML/Einstein.xml
clamscan ./XML/Enigma.xml
clamscan ./XML/FindAtHome.xml
clamscan ./XML/GPUGrid.xml
clamscan ./XML/GridcoinFinance.xml
clamscan ./XML/LHCatHome.xml
clamscan ./XML/LeidenClassic.xml
clamscan ./XML/MalariaControl.xml
clamscan ./XML/Milkyway.xml
clamscan ./XML/MindModeling.xml
clamscan ./XML/MooWrap.xml
clamscan ./XML/NFS.xml
clamscan ./XML/NumbersField.xml
clamscan ./XML/POEM.xml
clamscan ./XML/PrimeGrid.xml
clamscan ./XML/Rosetta.xml
clamscan ./XML/SAT.xml
clamscan ./XML/SETI.xml
clamscan ./XML/Skynet.xml
clamscan ./XML/WCG.xml
clamscan ./XML/YAFU.xml
clamscan ./XML/YOYO.xml
clamscan ./XML/vLHC.xml
clamscan ./XML/Sztaki.xml
clamscan ./XML/Wuprop.xml
clamscan ./XML/NNReport.csv